# Generated by Django 4.0.3 on 2022-04-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработан?'),
        ),
    ]
