# Generated by Django 4.0.3 on 2022-04-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=150, verbose_name='Наименование')),
                ('cost', models.CharField(max_length=150, verbose_name='Цена')),
                ('cost_sale', models.CharField(max_length=150, verbose_name='Цена по скидке')),
                ('desc', models.TextField(max_length=150, verbose_name='Описание')),
                ('img', models.ImageField(blank=True, upload_to='photos/product', verbose_name='Картинка')),
                ('is_published', models.BooleanField(blank=True, default=True, verbose_name='Опубликован?')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
